-- =============================================================================
--  Migration: auth — PIN hash and refresh-token sessions
-- =============================================================================
--  Part 1 generated by Prisma. Part 2 hand-written (see the note in the initial
--  migration): CHECK constraints Prisma cannot express.
-- =============================================================================

-- CreateEnum
CREATE TYPE "SessionRevocationReason" AS ENUM ('ROTATED', 'LOGGED_OUT', 'REUSE_DETECTED', 'EXPIRED', 'PASSWORD_CHANGED');

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "pin_hash" VARCHAR(255);

-- CreateTable
CREATE TABLE "sessions" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "family_id" UUID NOT NULL,
    "token_hash" VARCHAR(64) NOT NULL,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revoked_at" TIMESTAMPTZ(6),
    "revocation_reason" "SessionRevocationReason",
    "replaced_by_id" UUID,
    "user_agent" VARCHAR(255),
    "ip_address" VARCHAR(45),

    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "sessions_token_hash_key" ON "sessions"("token_hash");

-- CreateIndex
CREATE UNIQUE INDEX "sessions_replaced_by_id_key" ON "sessions"("replaced_by_id");

-- CreateIndex
CREATE INDEX "sessions_user_id_created_at_idx" ON "sessions"("user_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "sessions_family_id_idx" ON "sessions"("family_id");

-- CreateIndex
CREATE INDEX "sessions_expires_at_idx" ON "sessions"("expires_at");

-- AddForeignKey
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_replaced_by_id_fkey" FOREIGN KEY ("replaced_by_id") REFERENCES "sessions"("id") ON DELETE SET NULL ON UPDATE CASCADE;


-- =============================================================================
--  PART 2 — Hand-written integrity rules
-- =============================================================================

-- A revoked session must record both when it was revoked and why. Without this
-- a row could claim to be revoked while leaving the reason NULL, and the
-- security-relevant distinction between "rotated normally" and "revoked because
-- we detected token reuse" would be lost exactly when it matters most.
ALTER TABLE "sessions"
  ADD CONSTRAINT "chk_sessions_revocation_shape"
  CHECK (
    ("revoked_at" IS NULL     AND "revocation_reason" IS NULL) OR
    ("revoked_at" IS NOT NULL AND "revocation_reason" IS NOT NULL)
  );

-- A session cannot be its own replacement.
ALTER TABLE "sessions"
  ADD CONSTRAINT "chk_sessions_not_self_replacing"
  CHECK ("replaced_by_id" IS NULL OR "replaced_by_id" <> "id");

-- A session must expire after it was created.
ALTER TABLE "sessions"
  ADD CONSTRAINT "chk_sessions_expiry_after_creation"
  CHECK ("expires_at" > "created_at");

-- Fast path for the only query on the refresh route: find the live session for
-- a presented token. Partial, so the index covers active sessions only and does
-- not grow with revoked history.
CREATE INDEX "idx_sessions_active"
  ON "sessions" ("token_hash")
  WHERE "revoked_at" IS NULL;
