-- =============================================================================
--  Initial migration — Money Movement Application
--  PSTU IT Carnival 2026
-- =============================================================================
--
--  Part 1 is generated by Prisma from prisma/schema.prisma.
--
--  Part 2 is hand-written and is NOT recoverable from the Prisma schema: CHECK
--  constraints, partial and functional indexes, and the ledger immutability
--  trigger. Prisma's schema language cannot express any of them, so if this
--  file is ever regenerated from scratch, Part 2 must be carried across by
--  hand. Everything in Part 2 is load-bearing — these are the constraints that
--  make the invariants in docs/REQUIREMENTS.md true even when the application
--  logic is wrong.
--
--  Money is stored as BIGINT poisha (1 taka = 100 poisha). There is no float
--  anywhere in this schema; see the header of prisma/schema.prisma for why.
-- =============================================================================


-- =============================================================================
--  PART 1 — Generated by Prisma
-- =============================================================================

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'CLOSED');

-- CreateEnum
CREATE TYPE "AccountType" AS ENUM ('USER', 'SYSTEM');

-- CreateEnum
CREATE TYPE "AccountStatus" AS ENUM ('ACTIVE', 'FROZEN', 'CLOSED');

-- CreateEnum
CREATE TYPE "TransactionType" AS ENUM ('TRANSFER', 'SIGNUP_BONUS', 'REVERSAL');

-- CreateEnum
CREATE TYPE "TransactionStatus" AS ENUM ('PENDING', 'SUCCESS', 'FAILED', 'REVERSED');

-- CreateEnum
CREATE TYPE "TransactionFailureReason" AS ENUM ('INSUFFICIENT_FUNDS', 'SELF_TRANSFER', 'INVALID_AMOUNT', 'LIMIT_EXCEEDED', 'SENDER_ACCOUNT_FROZEN', 'RECEIVER_ACCOUNT_FROZEN', 'RECEIVER_NOT_FOUND', 'REQUEST_NOT_PENDING', 'INTERNAL_ERROR');

-- CreateEnum
CREATE TYPE "LedgerDirection" AS ENUM ('DEBIT', 'CREDIT');

-- CreateEnum
CREATE TYPE "MoneyRequestStatus" AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "IdempotencyState" AS ENUM ('IN_PROGRESS', 'COMPLETED', 'FAILED');

-- CreateEnum
CREATE TYPE "NotificationType" AS ENUM ('MONEY_RECEIVED', 'MONEY_SENT', 'REQUEST_RECEIVED', 'REQUEST_ACCEPTED', 'REQUEST_REJECTED', 'REQUEST_CANCELLED', 'SIGNUP_BONUS');

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "phone" VARCHAR(20) NOT NULL,
    "username" VARCHAR(50) NOT NULL,
    "password_hash" VARCHAR(255) NOT NULL,
    "display_name" VARCHAR(100) NOT NULL,
    "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "accounts" (
    "id" UUID NOT NULL,
    "user_id" UUID,
    "balance_poisha" BIGINT NOT NULL DEFAULT 0,
    "currency" VARCHAR(3) NOT NULL DEFAULT 'BDT',
    "account_type" "AccountType" NOT NULL DEFAULT 'USER',
    "status" "AccountStatus" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "accounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "transactions" (
    "id" UUID NOT NULL,
    "reference" VARCHAR(32) NOT NULL,
    "type" "TransactionType" NOT NULL,
    "status" "TransactionStatus" NOT NULL DEFAULT 'PENDING',
    "amount_poisha" BIGINT NOT NULL,
    "sender_account_id" UUID NOT NULL,
    "receiver_account_id" UUID,
    "note" VARCHAR(255),
    "failure_reason" "TransactionFailureReason",
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMPTZ(6),

    CONSTRAINT "transactions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ledger_entries" (
    "id" UUID NOT NULL,
    "transaction_id" UUID NOT NULL,
    "account_id" UUID NOT NULL,
    "direction" "LedgerDirection" NOT NULL,
    "amount_poisha" BIGINT NOT NULL,
    "balance_after_poisha" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ledger_entries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "money_requests" (
    "id" UUID NOT NULL,
    "reference" VARCHAR(32) NOT NULL,
    "requester_id" UUID NOT NULL,
    "requestee_id" UUID NOT NULL,
    "amount_poisha" BIGINT NOT NULL,
    "note" VARCHAR(255),
    "status" "MoneyRequestStatus" NOT NULL DEFAULT 'PENDING',
    "settled_transaction_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "responded_at" TIMESTAMPTZ(6),
    "expires_at" TIMESTAMPTZ(6),

    CONSTRAINT "money_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "idempotency_keys" (
    "id" UUID NOT NULL,
    "key" VARCHAR(255) NOT NULL,
    "user_id" UUID NOT NULL,
    "operation" VARCHAR(100) NOT NULL,
    "request_hash" VARCHAR(64) NOT NULL,
    "state" "IdempotencyState" NOT NULL DEFAULT 'IN_PROGRESS',
    "response_status" INTEGER,
    "response_body" JSONB,
    "transaction_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "idempotency_keys_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notifications" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "type" "NotificationType" NOT NULL,
    "title" VARCHAR(120) NOT NULL,
    "body" VARCHAR(500) NOT NULL,
    "payload" JSONB,
    "transaction_id" UUID,
    "money_request_id" UUID,
    "read_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "users_phone_key" ON "users"("phone");

-- CreateIndex
CREATE UNIQUE INDEX "users_username_key" ON "users"("username");

-- CreateIndex
CREATE INDEX "users_status_idx" ON "users"("status");

-- CreateIndex
CREATE UNIQUE INDEX "accounts_user_id_key" ON "accounts"("user_id");

-- CreateIndex
CREATE INDEX "accounts_account_type_idx" ON "accounts"("account_type");

-- CreateIndex
CREATE UNIQUE INDEX "transactions_reference_key" ON "transactions"("reference");

-- CreateIndex
CREATE INDEX "transactions_sender_account_id_created_at_id_idx" ON "transactions"("sender_account_id", "created_at" DESC, "id" DESC);

-- CreateIndex
CREATE INDEX "transactions_receiver_account_id_created_at_id_idx" ON "transactions"("receiver_account_id", "created_at" DESC, "id" DESC);

-- CreateIndex
CREATE INDEX "transactions_status_created_at_idx" ON "transactions"("status", "created_at" DESC);

-- CreateIndex
CREATE INDEX "ledger_entries_account_id_created_at_id_idx" ON "ledger_entries"("account_id", "created_at" DESC, "id" DESC);

-- CreateIndex
CREATE INDEX "ledger_entries_transaction_id_idx" ON "ledger_entries"("transaction_id");

-- CreateIndex
CREATE UNIQUE INDEX "money_requests_reference_key" ON "money_requests"("reference");

-- CreateIndex
CREATE UNIQUE INDEX "money_requests_settled_transaction_id_key" ON "money_requests"("settled_transaction_id");

-- CreateIndex
CREATE INDEX "money_requests_requestee_id_status_created_at_idx" ON "money_requests"("requestee_id", "status", "created_at" DESC);

-- CreateIndex
CREATE INDEX "money_requests_requester_id_status_created_at_idx" ON "money_requests"("requester_id", "status", "created_at" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "idempotency_keys_transaction_id_key" ON "idempotency_keys"("transaction_id");

-- CreateIndex
CREATE INDEX "idempotency_keys_expires_at_idx" ON "idempotency_keys"("expires_at");

-- CreateIndex
CREATE UNIQUE INDEX "uq_idempotency_keys_user_key" ON "idempotency_keys"("user_id", "key");

-- CreateIndex
CREATE INDEX "notifications_user_id_created_at_id_idx" ON "notifications"("user_id", "created_at" DESC, "id" DESC);

-- AddForeignKey
ALTER TABLE "accounts" ADD CONSTRAINT "accounts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_sender_account_id_fkey" FOREIGN KEY ("sender_account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_receiver_account_id_fkey" FOREIGN KEY ("receiver_account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ledger_entries" ADD CONSTRAINT "ledger_entries_transaction_id_fkey" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ledger_entries" ADD CONSTRAINT "ledger_entries_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "money_requests" ADD CONSTRAINT "money_requests_requester_id_fkey" FOREIGN KEY ("requester_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "money_requests" ADD CONSTRAINT "money_requests_requestee_id_fkey" FOREIGN KEY ("requestee_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "money_requests" ADD CONSTRAINT "money_requests_settled_transaction_id_fkey" FOREIGN KEY ("settled_transaction_id") REFERENCES "transactions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "idempotency_keys" ADD CONSTRAINT "idempotency_keys_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "idempotency_keys" ADD CONSTRAINT "idempotency_keys_transaction_id_fkey" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_transaction_id_fkey" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_money_request_id_fkey" FOREIGN KEY ("money_request_id") REFERENCES "money_requests"("id") ON DELETE CASCADE ON UPDATE CASCADE;



-- =============================================================================
--  PART 2 — Hand-written integrity rules
--  Not expressible in the Prisma schema. Preserve these across regeneration.
-- =============================================================================

-- -----------------------------------------------------------------------------
--  2.1  accounts
-- -----------------------------------------------------------------------------

-- A user wallet may never go negative. This is the last line of defence behind
-- the conditional UPDATE in the transfer path (NFR-A): even if the application
-- logic is wrong, an overdrawn user balance cannot be persisted.
--
-- The SYSTEM account is deliberately exempt, because it is the mint. Every
-- taka issued into the system (the ৳100,000 signup credit) is matched by an
-- equal debt on the SYSTEM account, whose balance is therefore the negative of
-- all money in circulation. That is what keeps the books at zero — see 2.8.
ALTER TABLE "accounts"
  ADD CONSTRAINT "chk_accounts_balance_sign"
  CHECK (
    "account_type" = 'SYSTEM' OR "balance_poisha" >= 0
  );

-- Closed single-currency ecosystem. Mixing units in an integer money column is
-- silent and catastrophic: 100 poisha and 100 cents would add together without
-- complaint. Multi-currency would require a per-currency balance and an
-- explicit conversion policy, not a second value in the same column.
ALTER TABLE "accounts"
  ADD CONSTRAINT "chk_accounts_currency"
  CHECK ("currency" = 'BDT');

-- Exactly one SYSTEM account may ever exist. Two mints would make the zero-sum
-- invariant unverifiable, because money could be issued from either.
CREATE UNIQUE INDEX "uq_accounts_one_system"
  ON "accounts" (("account_type"))
  WHERE "account_type" = 'SYSTEM';

-- A USER account must belong to a user; the SYSTEM account must not.
ALTER TABLE "accounts"
  ADD CONSTRAINT "chk_accounts_owner_shape"
  CHECK (
    ("account_type" = 'USER'   AND "user_id" IS NOT NULL) OR
    ("account_type" = 'SYSTEM' AND "user_id" IS NULL)
  );


-- -----------------------------------------------------------------------------
--  2.2  transactions
-- -----------------------------------------------------------------------------

-- Zero, negative and absurd amounts are rejected by the database, not merely by
-- a DTO validator (FR-09). A negative "transfer" is a withdrawal from the
-- recipient — the single most valuable constraint in this file to get right.
ALTER TABLE "transactions"
  ADD CONSTRAINT "chk_transactions_amount_positive"
  CHECK ("amount_poisha" > 0);

-- Self-transfer prevention (FR-08). Left as a real constraint rather than an
-- application check because a self-transfer that slipped through would produce
-- a DEBIT and a CREDIT on the same account, which nets to zero but pollutes the
-- ledger with a movement that never happened.
ALTER TABLE "transactions"
  ADD CONSTRAINT "chk_transactions_no_self_transfer"
  CHECK (
    "receiver_account_id" IS NULL OR
    "sender_account_id" <> "receiver_account_id"
  );

-- A transaction must be fully described by its terminal state. Without this, a
-- row could claim SUCCESS while having no recipient and no completion time —
-- an outcome nobody could audit.
--
--   SUCCESS  => receiver present, completed_at set, no failure reason
--   FAILED   => failure reason present, completed_at set
--   PENDING  => not yet completed
ALTER TABLE "transactions"
  ADD CONSTRAINT "chk_transactions_status_shape"
  CHECK (
    (
      "status" = 'SUCCESS'
      AND "receiver_account_id" IS NOT NULL
      AND "completed_at" IS NOT NULL
      AND "failure_reason" IS NULL
    ) OR (
      "status" = 'FAILED'
      AND "failure_reason" IS NOT NULL
      AND "completed_at" IS NOT NULL
    ) OR (
      "status" = 'PENDING'
      AND "completed_at" IS NULL
      AND "failure_reason" IS NULL
    ) OR (
      "status" = 'REVERSED'
      AND "completed_at" IS NOT NULL
    )
  );


-- -----------------------------------------------------------------------------
--  2.3  ledger_entries
-- -----------------------------------------------------------------------------

-- Magnitude only. Direction is carried by the DEBIT/CREDIT column and never by
-- the sign of the amount — a signed amount *plus* a direction column is a
-- double negative waiting to be applied twice.
ALTER TABLE "ledger_entries"
  ADD CONSTRAINT "chk_ledger_entries_amount_positive"
  CHECK ("amount_poisha" > 0);


-- -----------------------------------------------------------------------------
--  2.4  THE LEDGER IS INSERT-ONLY
-- -----------------------------------------------------------------------------
--
-- The application contract is that `ledger_entries` is append-only: the
-- repository exposes only create/createMany, and no update or delete method
-- exists to be called by accident. A mistake is corrected by inserting a
-- compensating REVERSAL entry, never by amending or removing the original.
--
-- PostgreSQL has no native "immutable table" declaration, so that contract
-- would otherwise be a comment and nothing more. This trigger makes it real.
-- It is defence in depth, not a replacement for the application rule: it turns
-- "we agreed not to do that" into "the database refuses".
--
-- Why it matters: a ledger whose rows can change after the fact is a report,
-- not an audit trail. If a row can be edited, replaying the entries to verify a
-- balance proves nothing, and there is no way to tell a correction from a
-- cover-up. Immutability is the property that makes the history evidence.
--
-- To alter this table in a future migration, drop the trigger explicitly,
-- migrate, and recreate it. That is deliberately a conscious act.
CREATE OR REPLACE FUNCTION "ledger_entries_forbid_mutation"()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION
    'ledger_entries is append-only: % on row % is not permitted. '
    'Correct a mistake by inserting a compensating REVERSAL entry.',
    TG_OP, COALESCE(OLD."id"::text, '(unknown)')
    USING ERRCODE = 'restrict_violation';
END;
$$;

CREATE TRIGGER "trg_ledger_entries_immutable"
  BEFORE UPDATE OR DELETE ON "ledger_entries"
  FOR EACH ROW
  EXECUTE FUNCTION "ledger_entries_forbid_mutation"();

-- Blocks TRUNCATE too, which bypasses row-level triggers entirely.
CREATE TRIGGER "trg_ledger_entries_no_truncate"
  BEFORE TRUNCATE ON "ledger_entries"
  FOR EACH STATEMENT
  EXECUTE FUNCTION "ledger_entries_forbid_mutation"();


-- -----------------------------------------------------------------------------
--  2.5  money_requests
-- -----------------------------------------------------------------------------

ALTER TABLE "money_requests"
  ADD CONSTRAINT "chk_money_requests_amount_positive"
  CHECK ("amount_poisha" > 0);

-- You cannot bill yourself.
ALTER TABLE "money_requests"
  ADD CONSTRAINT "chk_money_requests_not_self"
  CHECK ("requester_id" <> "requestee_id");

-- Makes "accepted but no money moved" unrepresentable (FR-C): an ACCEPTED
-- request must point at the transaction that settled it, and a request still
-- PENDING must not point at one.
ALTER TABLE "money_requests"
  ADD CONSTRAINT "chk_money_requests_settlement_shape"
  CHECK (
    (
      "status" = 'ACCEPTED'
      AND "settled_transaction_id" IS NOT NULL
      AND "responded_at" IS NOT NULL
    ) OR (
      "status" = 'PENDING'
      AND "settled_transaction_id" IS NULL
      AND "responded_at" IS NULL
    ) OR (
      "status" IN ('REJECTED', 'CANCELLED', 'EXPIRED')
      AND "settled_transaction_id" IS NULL
    )
  );

-- At most one outstanding request between the same pair for the same amount.
-- Blunts accidental duplicate submissions without preventing a user from
-- legitimately requesting a different amount.
CREATE UNIQUE INDEX "uq_money_requests_pending_pair"
  ON "money_requests" ("requester_id", "requestee_id", "amount_poisha")
  WHERE "status" = 'PENDING';


-- -----------------------------------------------------------------------------
--  2.6  idempotency_keys
-- -----------------------------------------------------------------------------
--
-- The UNIQUE (user_id, key) index created in Part 1 IS the deduplication
-- mechanism (NFR-B). A "check if it exists, then insert" sequence is itself a
-- race; here the second concurrent writer loses on the constraint and reads
-- back the winner's stored response.

-- A COMPLETED key must carry the response it will replay, or a retry would
-- return an empty body and the client could not distinguish it from a failure.
ALTER TABLE "idempotency_keys"
  ADD CONSTRAINT "chk_idempotency_keys_completed_shape"
  CHECK (
    "state" <> 'COMPLETED' OR "response_status" IS NOT NULL
  );


-- -----------------------------------------------------------------------------
--  2.7  Case-insensitive lookup (FR-05)
-- -----------------------------------------------------------------------------
--
-- Prisma cannot express expression indexes. Without these, a case-insensitive
-- login or user search degrades to a sequential scan — fine at ten users, fatal
-- at the ten million the brief projects (NFR-D).
--
-- These are UNIQUE, so "Alice@example.com" and "alice@example.com" cannot both
-- register. Two accounts differing only by case is an account-takeover vector,
-- not a cosmetic issue.
CREATE UNIQUE INDEX "uq_users_email_lower" ON "users" (lower("email"));
CREATE UNIQUE INDEX "uq_users_username_lower" ON "users" (lower("username"));

-- Unread-notification badge; partial so the index stays small as history grows.
CREATE INDEX "idx_notifications_unread"
  ON "notifications" ("user_id", "created_at" DESC)
  WHERE "read_at" IS NULL;


-- -----------------------------------------------------------------------------
--  2.8  The global invariant, as a runnable check
-- -----------------------------------------------------------------------------
--
-- Double-entry bookkeeping means money is only ever moved, never created or
-- destroyed. Because new money enters through the SYSTEM account as negative
-- balance, the sum across ALL accounts must be exactly zero at every committed
-- state. This view makes that assertable in one query, by a test, a monitor, or
-- a judge at a demo:
--
--     SELECT * FROM "v_money_invariant";
--
-- `is_balanced` must be true. If it is ever false, money has leaked and the
-- system has a bug — no further reasoning required.
CREATE VIEW "v_money_invariant" AS
SELECT
  COALESCE(SUM("balance_poisha"), 0)                        AS total_balance_poisha,
  COALESCE(SUM("balance_poisha") FILTER (
    WHERE "account_type" = 'USER'), 0)                      AS user_balance_poisha,
  COALESCE(SUM("balance_poisha") FILTER (
    WHERE "account_type" = 'SYSTEM'), 0)                    AS system_balance_poisha,
  COALESCE(SUM("balance_poisha"), 0) = 0                    AS is_balanced
FROM "accounts";

-- Every transaction's ledger entries must net to zero, and there must be at
-- least two of them. A transaction that debited without crediting would show up
-- here immediately.
CREATE VIEW "v_unbalanced_transactions" AS
SELECT
  t."id"                AS transaction_id,
  t."reference"         AS reference,
  t."status"            AS status,
  COUNT(le."id")        AS entry_count,
  COALESCE(SUM(
    CASE le."direction"
      WHEN 'CREDIT' THEN le."amount_poisha"
      WHEN 'DEBIT'  THEN -le."amount_poisha"
    END
  ), 0)                 AS net_poisha
FROM "transactions" t
LEFT JOIN "ledger_entries" le ON le."transaction_id" = t."id"
WHERE t."status" = 'SUCCESS'
GROUP BY t."id", t."reference", t."status"
HAVING COALESCE(SUM(
  CASE le."direction"
    WHEN 'CREDIT' THEN le."amount_poisha"
    WHEN 'DEBIT'  THEN -le."amount_poisha"
  END
), 0) <> 0
   OR COUNT(le."id") < 2;
